### ISSUE TITLE
[QUESTION] mismatch between the obtained target dummy in simulation (vrep) and matlab:

### ISSUE THREAD

**Issue by fahmizo** [dqrobotics/matlab#85] opened 2023-02-02 16:52 UTC
Acceptance of the Code of Conduct
Leave these in your question, read, and check them.

- [ ✔] I understand that support for DQRobotics is given voluntarily.

- [✔ ]  I understand that any possible response and its timeliness will be based on the relevance, accuracy, and politeness of my request and the following discussion.

 

- [ ✔] If a DQRobotics member replies, I will let them know, politely, if their response solves my issue or not.

---------------------------------------------------------------------------------------------------
Firstly, i apologise for not properly addressing the problem and not committing to the guidlines.

My question is related to providing the desired pose dual quaternion using the dq_vrepinterface  for the pseudoinverse to calculate the error between poses in the simulation.

I currently have my dynamics engine disabled and the intentions for my code is obtaining a dummy pose as a target, then control the end effector's pose from a given intial configuration to the desired target.

i have checked if i can retrieve information from the simulation, as just the target dummy's pose is shown successfully however, when using the target pose in the control loop it does not provide the correct robot configurations in the simulation and for reference i have had my base frame aligned with the world frame for the target's relative pose.

the following code was used for obtaining the mentioned process:
`clear all;
close all;
clc;
vi = DQ_VrepInterface();
vi.disconnect_all();
vi.connect('127.0.0.1',19997);
vi.start_simulation();

include_namespace_dq
kuka = KukaLwr4Robot.kinematics()
kuka.name = 'KUKA';

    %getting joint handles:
    joints={'joint1','joint2','joint3','joint4','joint5','joint6','joint7'};
    vi.get_handles(joints);

    %Initial configuration
    qstart =[0    -pi/2    pi/2   -0.5655         0         0         0]';
    vi.set_joint_positions(joints,qstart,vi.OP_ONESHOT);
    %Final configuration
    qd = [0.1527   -1.5971    0.0002    1.5969    0.0044   -3.0892   -0.1483]';
    q = qstart;

    epsilon = 0.001; %The error must be bellow this value in order to stop the robot
    gain = 0.1; %Gain of the controllers

    xd = kuka.fkm(qd); %Desired end-effector's pose
     %this is where i miss up:
    Target= vi.get_handle('Target');
    td=vi.get_object_pose('Target');
    td=translation(td);
    xdd=1+ E_*0.5*td*1
    

    figure;
    axis equal;
    plot(kuka, q);
    view(-0,0)
    hold on;
    plot(kuka, q);
    plot(xdd)
    
    

    fprintf('Performing standard kinematic control using dual quaternion coordinates');
    x = kuka.fkm(q);
    e = epsilon+1;
    while norm(e) > epsilon
        J = kuka.pose_jacobian(q);
        x = kuka.fkm(q);
        e = vec8(xdd-x);
        q = q+pinv(J)*gain*e;
        plot(kuka, q');    
        drawnow;
        vi.set_joint_positions(joints,q,vi.OP_STREAMING);
    end
vi.stop_simulation();
vi.disconnect();
`
when the code is run it provides the desired target in matlab and the desired configurations, however at the same instance its it completely different over on vrep.
<img width="416" alt="matlabkuka" src="https://user-images.githubusercontent.com/53474646/216675067-5c9891d1-0660-4bf0-b9d5-faa7c83ff842.png">
<img width="499" alt="kukavrep" src="https://user-images.githubusercontent.com/53474646/216675091-88d2ab62-267a-4a80-ab9a-dbea9e477cad.png">

i have tried implementing the function DQ_PseudoinverseController() as follows:
`
pose_controller = DQ_PseudoinverseController(kuka);
    pose_controller.set_control_objective(ControlObjective.Pose)
    pose_controller.set_gain(gain)
   
    tau = 0.05; 
    % Simulation time [s]
    final_time = 1;
    

% Translation controller loop.
for time=0:tau:final_time
    % Get the next control signal [rad/s]
    u = pose_controller.compute_setpoint_control_signal(q,vec8(pose_target));
    
    % Move the robot
    q = q + u*tau;
    vi.set_joint_positions(joints,q);
end
`
but it was almost the same issue
Environment:

OS: [e.g. Windows 11]
dqrobotics version (current version of the master branch)
MATLAB R2022b
CoppeliaSimedu version 4.4.0

[inverse_sample_dummies.zip](https://github.com/dqrobotics/matlab/files/10581659/inverse_sample_dummies.zip)

**Comment by bvadorno** [comment] 2023-02-02 20:54
Hi @fahmizo,

Thank you for posting your question and engaging with the DQ Robotics community. We have a strict policy in which anyone raising a question must accept the Code of Conduct automatically generated when you start an issue. Usually, when people fail to comply with this very simple request, we close the issue automatically. Nonetheless, since this is your first time, I'll guide you through the procedure.

1. First, include at the beginning of your question what you shouldn't have deleted:
> ### Acceptance of the Code of Conduct
> _Leave these in your question, read, and check them._ 
> - [ ] I understand that support for DQRobotics is given voluntarily. 
> - [ ] I understand that any possible response and its timeliness will be based on the relevance, accuracy, and politeness of my request and the following discussion.
> - [ ] If a DQRobotics member replies, I will let them know, politely, if their response solves my issue or not. 

2. The [MWE](https://stackoverflow.com/help/minimal-reproducible-example) should be placed directly in the issue you opened (i.e., this interface) using Markdown language, not in a separate file. You can find how to include code directly on the web interface [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). An example of what we expect can be found [here](https://github.com/dqrobotics/matlab/issues/76).

3. Your code is currently irreproducible because you haven't provided the CoppeliaSim scene file you are using. You must do it (and being a CoppeliaSim file, not a source code, you can attach it.) Also, you haven't provided basic details: is the dynamics engine activated? Can you retrieve basic information from CoppeliaSim, such as the end-effector pose at different configurations? (This is something that you can easily compare with the MATLAB output.) What is the CoppeliaSim version you are using? What is your operating system? Also, without knowing if you can send and get information from CoppeliaSim **correctly**, it is pointless to discuss if the controller works or not.
 
After you solve all three aforementioned items, we can proceed.

I'm assigning @juanjqo to this issue, together with myself, and hopefully, we can help you with your problem.

Kind regards,
Bruno

**Comment by juanjqo** [comment] 2023-02-06 07:00
Hi @fahmizo, 

Welcome to the DQ Robotics community. Thank you for providing more information about your issue. I reproduced the behavior you mentioned, which is expected, according to your code and your scene. 

There are several contributing factors to your simulation not working.

### 1. Dynamics engine
The robot moves when you run the simulation from CoppeliaSim (without any script from Matlab).  This is because the dynamics engine is activated and there are low-level controllers acting on all joints. 

<img src="https://user-images.githubusercontent.com/23158313/216883805-d23e05cd-0dab-4bb4-954b-c6affc8cdeb1.gif" alt="drawing" width="600"/>

In your specific scene, you are using the joints in `dynamic mode` and `control position mode`. Therefore, there is a PID controller trying to minimize the error between the current angle and the target angle (This dynamic is handled by the physics engine, which in your scene is the Bullet engine). In those cases, you need to set the target angles by using `set_joint_target_positions(jointnames, qtarget)` instead of `set_joint_positions(jointnames, q)`.

<img src="https://user-images.githubusercontent.com/23158313/216883083-be5e982e-4a28-4010-add8-785c315238a5.png" alt="drawing" width="600"/>

If your goal is to use CoppeliaSim only as a visualization tool (no dynamics), you need to set the joints to `Kinematic Mode` and disable the dynamics of the robot links (uncheck the box `Body is dynamic` in Rigid Body Dynamic Properties).
Example:
<img src="https://user-images.githubusercontent.com/23158313/216889043-93d6c375-fba2-4483-aa0d-c594a01eeed2.png" alt="drawing" width="400"/>

<img src="https://user-images.githubusercontent.com/23158313/216889217-bd38129b-23a8-4f2b-97b7-530a962f11e3.png" alt="drawing" width="400"/>

### 2. Wrong joint names

It looks like you edited the joint names of the robot in your scene. However, the sixth joint is called `joint` in the scene and `joint6` in your code. 

```matlab
joints={'joint1','joint2','joint3','joint4','joint5','joint6','joint7'};
```
<img src="https://user-images.githubusercontent.com/23158313/216891082-139d6696-516e-4d14-bf4f-8511ffc48938.png" alt="drawing" width="400"/>

### 3. Wrong robot model 

According to your code, you are modeling the KUKA LBR4 manipulator. However, you are using on CoppeliaSim a different manipulator (KUKA LBR iiwa 14 R820).  This will lead to modeling errors. Furthermore, the KukaLwr4Robot() class does not provide the right kinematic model for the KUKA LBR4+ manipulator available on CoppeliaSim.

----------------------------------

# Working Example

<img src="https://user-images.githubusercontent.com/23158313/216903456-afa99116-52aa-427a-aadf-83b1770836c2.gif" alt="drawing" width="600"/>

Please find attached a minimal example using the KUKA LBR4+ manipulator with the joints in kinematic mode (no dynamics).

```matlab
clear all;
close all;
clc;
vi = DQ_VrepInterface();
vi.disconnect_all();
vi.connect('127.0.0.1',19997);
vi.start_simulation();

jointnames={'LBR4p_joint1','LBR4p_joint2',...
            'LBR4p_joint3','LBR4p_joint4',...
            'LBR4p_joint5','LBR4p_joint6',...
            'LBR4p_joint7'};

%---------------------Robot definition--------------------------%
LBR4p_DH_theta = [0, 0, 0, 0, 0, 0, 0];
LBR4p_DH_d = [0.200, 0, 0.4, 0, 0.39, 0, 0];
LBR4p_DH_a = [0, 0, 0, 0, 0, 0, 0];
LBR4p_DH_alpha = [pi/2, -pi/2, pi/2, -pi/2, pi/2, -pi/2, 0];
LBR4p_DH_type = double(repmat(DQ_JointType.REVOLUTE,1,7));
LBR4p_DH_matrix = [LBR4p_DH_theta;
                    LBR4p_DH_d;
                    LBR4p_DH_a;
                    LBR4p_DH_alpha
                    LBR4p_DH_type];
            
robot = DQ_SerialManipulatorDH(LBR4p_DH_matrix);
xbase = vi.get_object_pose('LBR4p_joint1');
robot.set_reference_frame(xbase);
robot.set_base_frame(xbase);
robot.set_effector(1+0.5*DQ.E*DQ.k*0.07);
%----------------------------------------------------------------

%---------------------Controller definition----------------------%
controller = DQ_PseudoinverseController(robot);
controller.set_gain(0.5);
controller.set_damping(0.01);
controller.set_control_objective(ControlObjective.Translation)
controller.set_stability_threshold(0.00001);
%----------------------------------------------------------------

q = vi.get_joint_positions(jointnames);
T = 0.01;
while ~controller.system_reached_stable_region()
    xd = vi.get_object_pose('target');
    u = controller.compute_setpoint_control_signal(q, vec4(translation(xd)));
    q = q + T*u;
    vi.set_joint_positions(jointnames, q);
    vi.set_object_pose('effector', robot.fkm(q))
    vi.set_object_pose('base', xbase);
end


vi.stop_simulation();
vi.disconnect();
```

[kinematicMode_noDynamics.zip](https://github.com/dqrobotics/matlab/files/10660379/kinematicMode_noDynamics.zip)

**Comment by fahmizo** [comment] 2023-02-06 10:48
hello, 
I hope you are okay and thank you for the welcoming.
your comments have been very constructive and enlightening, you've helped me point out other functions  for my specific model as well as point out what is wrong with my old code.
I really appreciate the detailed feedback,
thank you.

**Comment by juanjqo** [comment] 2023-02-06 11:48
@fahmizo I'm glad to help you. If you have any questions, please feel free to ask.

**Comment by bvadorno** [comment] 2023-04-01 17:18
@juanjqo, your minimal examples are awesome. I'm going to close this issue because it's been solved, but we should create a zero to hero tutorial using CoppeliaSim as well. Do you want to lead this initiative together with @ffasilva?  

All the best,
Bruno

**Closed by bvadorno** 2023-04-01 17:18 UTC
Labels: question

**Comment by juanjqo** [comment] 2023-04-02 09:02
Hi @bvadorno, sure! That would be great! I'll work on it.

Best regards,

Juancho
